### ISSUE TITLE
Role Names

### ISSUE THREAD

**Issue by NilsPetras** [NilsPetras/IPV#10]
Including Ulf-Dietrich Reips, my supervisor, and Michael Dantlgraber, author of the concept, and feedback giver, I find it hard to match them to some predefined roles. Currently I have them as "ths" (thesis advisor) and "ccp" (conceptor). Is that matching common standards? Alternatively I could imagine to simply add them as ctb's or not at all (which they would dislike understandably), if that matches the common standard.

**Comment by mbannert** [comment]
I'd go with adding everyone who helped, advised with this as an author [aut] or [ctb]. What basically counts and shifts focus to you as being the maintainer of the package [aut,cre]. At least this is what I do and so far it kept everybody involved happy. credit where credit is due :100:
