### ISSUE TITLE
function names and style

### ISSUE THREAD

**Issue by mbannert** [NilsPetras/IPV#2]
As long as you do not use S3 methods you should do something like `my.function` it's either
`myFunction` or `my_function`. I suggest to go with the latter. 

Also remove the fbrv prefix from the functions, your package has a namespace which does exactly that. 
some functions, e.g., calc will need a bit of a more telling name then.

**Comment by NilsPetras** [comment]
After changing the names according to your guidelines i also changed the function calls. E.g. model_nested calls model_facets. If the namespace redefines anything, do i also need to change it in the code?

**Comment by mbannert** [comment]
yes, all function calls have to be changed if the name of the function changes. Good editors like sublime text 3 do it recursively for entire folders.
