### ISSUE TITLE
add roxygen style parameter documentation to all functions

### ISSUE THREAD

**Issue by mbannert** [NilsPetras/IPV#6]
just like here: 

https://github.com/NilsPetras/FBRV-in-R/blob/pkgdev/R/plot_factors.R

**Comment by NilsPetras** [comment]
do i need "@export" and how do i set it up correctly?

**Comment by mbannert** [comment]
@export simply means it's exported to the package namespace in such a way that users can call the function. In other words simply say

#'@export 

whenever you want **endusers** to use the function and don't do it if it's just helper function called by another function.
