### ISSUE TITLE
setting up for the usability test

### ISSUE THREAD

**Issue by NilsPetras** [NilsPetras/IPV#8]
How do we best provide the package to the people doing the usability test? As I guess the package will not be in the CRAN by then.

**Comment by mbannert** [comment]
Depends on who the testers are? 

A common way is to use the `devtools` package (on CRAN) and run install_github("NilsPetras/IPV") to install it directly from github. If your testers do not manage to install the package that way, just dish out .tar.gz files via e-mail or memory sticks and make them run `install.packages("ipv.tar.gz",repos=NULL) which is what I do with students who are reluctant to use github. Works pretty well and covers most target groups that would actually use an R package.

**Comment by NilsPetras** [comment]
I set both up and both work for me.
